#!/bin/sh
#
#   Copyright 2014 Venkat Palivela
#   Created by: Venkat Palivela and Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/envcov.sh
NOW=$(date +"%m-%d-%Y")
CI_DIR="${DIR}/../build/reports-$NOW"
LCOV_INFO="${DIR}/../build/Coverage.info"

remove_old_report()
{
    pushd ${CI_DIR}
    if [ -e lcov ]; then
        rm -r lcov
    fi
    popd
}

enter_lcov_dir()
{
    cd ${CI_DIR}
    mkdir lcov
    cd lcov
}

gather_coverage()
{
    LCOV --capture --derive-func-data -b "${SRCROOT}" -d "${OBJ_DIR}" -o ${LCOV_INFO}
}

exclude_data()
{
    LCOV --remove ${LCOV_INFO} "Developer/SDKs/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    LCOV --remove ${LCOV_INFO} "main.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    # Remove other patterns here...
}

generate_report()
{
    "${LCOV_PATH}/genhtml" --output-directory . ${LCOV_INFO}
    # open index.html
}

remove_old_report
enter_lcov_dir
gather_coverage
exclude_data
enter_lcov_dir
generate_report
